<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Multi Location Inventory</h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label for="multilocationinventory_global_inventory"><?php echo $this->__('Global Inventory') ?></label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $this->getGlobalInventory() ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="multilocationinventory_global_location"><?php echo $this->__('Scope Inventory') ?></label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $this->getScopeInventory() ?></span>
                    </td>
                </tr>
            </table>
        </div>
        <div>&nbsp;</div>
        <div>&nbsp;</div>
        <div class="grid">
            <table cellspacing="0" class="data border">
                <thead>
                <tr class="headings">
                    <th><?php echo $this->__('Location') ?></th>
                    <th><?php echo $this->__('Quantity') ?></th>
                    <th><?php echo $this->__('Qty for Item\'s Status to Become Out of Stock') ?></th>
                    <th><?php echo $this->__('Backorders') ?></th>
                    <th><?php echo $this->__('Stock Status') ?></th>
                    <th><?php echo $this->__('Manage Stock') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getLocationsInventories() as $_location): ?>
                    <tr>
                        <td>
                            <?php echo $_location['name'] ?>
                        </td>
                        <td>
                            <input type="text"
                                   name="multilocationinventory[<?php echo $_location['id'] ?>][quantity]"
                                   class="input-text validate-number"
                                   <?php echo ($_location['manage_stock'] === "1") ? '' : 'style="visibility:hidden;"' ?>
                                   value="<?php echo $_location['qty'] ?>"/>
                        </td>
                        <td>
                            <input type="text"
                                   name="multilocationinventory[<?php echo $_location['id'] ?>][min_qty]"
                                   class="input-text validate-number"
                                <?php echo ($_location['manage_stock'] === "1") ? '' : 'style="visibility:hidden;"' ?>
                                   value="<?php echo $_location['min_qty'] ?>"/>
                        </td>
                        <td>
                            <select name="multilocationinventory[<?php echo $_location['id'] ?>][backorders]"
                                    style="width:86%;<?php echo ($_location['manage_stock'] === "1") ? '' : 'visibility:hidden;' ?>" class="select">
                                <?php if($_location['backorders'] == ''): ?>
                                    <option value="-"></option>
                                <?php endif; ?>
                                <option
                                    value="1" <?php echo ($_location['backorders'] === "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('Yes') ?>
                                </option>
                                <option
                                    value="0" <?php echo ($_location['backorders'] !== "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('No') ?>
                                </option>
                            </select>
                        </td>
                        <td>
                            <select name="multilocationinventory[<?php echo $_location['id'] ?>][is_in_stock]"
                                    style="width:86%;<?php echo ($_location['manage_stock'] === "1") ? '' : 'visibility:hidden;' ?>" class="select">
                                <option
                                    value="1" <?php echo ($_location['is_in_stock'] === "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('In Stock') ?>
                                </option>
                                <option
                                    value="0" <?php echo ($_location['is_in_stock'] !== "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('Out Of Stock') ?>
                                </option>
                            </select>
                        </td>
                        <td>
                            <select name="multilocationinventory[<?php echo $_location['id'] ?>][manage_stock]"
                                    style="width:86%;" class="select demac_multilocationinventory_manage_stock">
                                <option
                                    value="1" <?php echo ($_location['manage_stock'] === "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('Yes') ?>
                                </option>
                                <option
                                    value="0" <?php echo ($_location['manage_stock'] !== "1") ? 'selected="selected"' : '' ?>>
                                    <?php echo $this->__('No') ?>
                                </option>
                            </select>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
$$('.demac_multilocationinventory_manage_stock').each(function(element) {
  element.observe('change', function (ev) {
    var visibility_str = "hidden";
    if(ev.target.value == "1") {
      visibility_str = "visible";
    }
    ev.target.parentElement.parentElement.select('input, select').each(function(toggleElement) {
      if(!toggleElement.hasClassName('demac_multilocationinventory_manage_stock')) {
        toggleElement.setStyle({visibility: visibility_str});
      }
    });
  });
});
</script>
