<h2><?php echo $this->__('Store Locator'); ?></h2>
<div id="locator_search">
    <label for="address"><?php echo $this->__('Please put your address : '); ?></label>
    <input type="text" name="address" id="address" value="<?php echo $this->getAddress() ?>" class="input-text"/>

    <p>
        <a href="#" onclick="initGeoloc(); return false;"
           title="<?php echo $this->__('Detect My Location') ?>"><?php echo $this->__('Detect My Location') ?></a>
        <?php if ($this->getSavedLocation()): ?>
            <span><?php echo $this->__(' - ') ?></span>
            <a href="#" onclick="$('clear_location').value = 1; $('closest_store_form').submit()"
               title="<?php echo $this->__('Clear saved location') ?>"><?php echo $this->__('Clear saved location') ?></a>
        <?php endif; ?>
    </p>
    <?php echo $this->getSavedLocationTitle(); ?>
</div>
<form id="closest_store_form" action="<?php echo $this->getUrl('demac_multilocationinventory/index/saveLocation'); ?>">

    <input type="hidden" name="default_location" id="default_location"
           value="<?php echo $this->getSavedLocationAddress(); ?>"/>
    <input type="hidden" name="clear_location" id="clear_location"
           value="0"/>
    <input type="hidden" name="saved_location" id="saved_location"
           value=""/>


    <div class="store-list">
        <?php foreach ($this->getStores() as $store) : ?>
            <table id="store-table" class="store-table">
                <tbody>
                <tr>
                    <td rowspan="8" class="store-image">
                        <img src="<?php echo $store->getImage(); ?>" alt="<?php echo $store->getName() ?>" width="150">
                    </td>
                </tr>
                <tr>
                    <td>
                        <h3 class='store-name'
                            id="store<?php echo $store->getId(); ?>"><?php echo $store->getName() ?></h3>
                    </td>
                </tr>
                <tr>
                    <td class="col-address">
                        <?php echo $store->getAddress() ?>
                    </td>
                </tr>
                <tr>
                    <td class="col-address">
                        <?php echo $store->getZipcode() . " " . $store->getCity() ?>
                    </td>
                </tr>
                <tr>
                    <td class="col-address">
                        <?php echo $store->getCountryId(); ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php if (!is_null($store->getStoreUrl()) && $store->getStoreUrl() != ''): ?>
                            <?php echo $this->__('Website :') ?><a href='<?php echo $store->getStoreUrl() ?>'
                                                                   target='_blank'><?php echo $this->__('%s', $store->getStoreUrl()); ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php if (!is_null($store->getPhone()) && $store->getPhone() != ''): ?>
                            <?php echo $this->__('Phone : %s', $store->getPhone()); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php if (!is_null($store->getFax()) && $store->getFax() != ''): ?>
                            <?php echo $this->__('Fax : %s', $store->getFax()); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <a href="#" class="store-save" onclick="saveLocation(<?php echo $store->getId(); ?>)"
                           title="<?php echo $this->__('Save this location') ?>"><?php echo $this->__('Save this location') ?></a>

                    </td>
                </tr>
                </tbody>
            </table>
        <?php endforeach; ?>
    </div>
</form>
<div id="maps">
    <div id="map_canvas"></div>
</div>
<div id="panel"></div>


<script type="text/javascript">
    var estimateDirectionLabel = '<?php echo $this->__('Get Directions'); ?>';
    var gmapUrl = '<?php echo $this->getGoogleApiUrl(); ?>';
    var apiSensor = '<?php echo Mage::getStoreConfig('demac_multilocationinventory/general/apisensor'); ?>';
    var stores = <?php echo Mage::helper('core')->jsonEncode($this->getStores()->toArray()); ?>;
    var mediaUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
    var pathMarker = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
    var defaultMarker = '<?php echo $this->getDefaultMarker(); ?>';
    var directionEnable = '<?php echo Mage::getStoreConfig('demac_multilocationinventory/general/direction'); ?>';
    var closestAmount = '<?php echo Mage::getStoreConfig('demac_multilocationinventory/general/closest_amount'); ?>';
    window.onload = loadScript;
</script>
